### ISSUE TITLE
Updates to data release before manuscript submission Feb 27th

### ISSUE THREAD

**Issue by msleckman** [USGS-R/forecast-data-release-v2#16]
### Updates to data release before manuscript submission Feb 27th

**To do:** 
- [x] 1. Update data files stored in `/in_data/` and elsewhere. Go to `~/data_releases/forecast-data-release-v2/in_data/` in caldera and swap out old files with new data  @jzwart
_Note: 1) blocking the following steps_  
   - [x] During/after data transfer in the dir, document which data files were swapped:
      - What are new dataset transformation are needed for new data if you know (e.g. feather to csv file format conversion)
      - What are the needed changes to the metadata descriptions of the new data 
- [x] 2. Update scipiper pipeline and the metadata of modified data files, using guidance provided in 1. @msleckman   
- [x] 3. Update date range in `text_04_predictions.yml` for `forecast_pgdl_da_outputs.zip` (if still applicable following data updates in 1.) @msleckman 
  - [x] [L139](https://github.com/USGS-R/forecast-data-release-v2/blob/0ddf948ee6504bdd4f8ded3e32a5c76dba51b4f7/in_text/text_04_predictions.yml#L139) 
  - [x] [L216](https://github.com/USGS-R/forecast-data-release-v2/blob/0ddf948ee6504bdd4f8ded3e32a5c76dba51b4f7/in_text/text_04_predictions.yml#L216)
  - [x] [L239-L248](https://github.com/USGS-R/forecast-data-release-v2/blob/0ddf948ee6504bdd4f8ded3e32a5c76dba51b4f7/in_text/text_04_predictions.yml#L239-L248)

- [x] Review summaries for parent and each child sb items and ensure descriptions are up to date with lates data changes (e.g. do we need more info under [3) config](https://www.sciencebase.gov/catalog/item/624f21ddd34e21f82769a7af) summary in sb? ) @msleckman @jzwart 

- [x] Push final changes to sciencebase and re-send to reviewer (@amsnyder  agreed to quick re-review nxt week (feb 20th). @msleckman

**Comment by jzwart** [comment]
@msleckman I added: 

- `in_data/all_mods_with_obs.feather` that should be used instead of `in_data/all_mods_with_obs.rds` 
- more `.nc` files to the `in_data/noaagefs_meteo_driver_files/` to fill out the dates to Sept 30, 2022 (previously only went to April 18, 2022) 
- `.nc` and `.xml` forecast files to `in_data/PGDL-DA/` from all our model experiments and I moved all the old forecast files to `in_data/PGDL-DA-old/` for safe keeping for now

I'm pretty confident everything else in `in_data/` stays the same. 

the forecast and `.xml`  files in `in_data/PGDL-DA/` amount to ~82Gb so I don't think we'll be able to zip up these files and have them available for a single download from ScienceBase. We could either leave them as individual files which would be >300 files or zip them up based on groups (e.g., model type)
